name: arduino_cli
 
on: [push, pull_request]
 
jobs:
  test-matrix:
    strategy:
      matrix:
        arduino-platform: ["arduino:avr"]
        include:
          - arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:uno"

    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
 
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
 
      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.arduino:avr:uno }} ./blink
