name: Arduino CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Target Branch'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Arduino
        uses: arduino/setup-arduino-cli@v1

      - name: Install Arduino Libraries
        run: |
          arduino-cli lib install servo
          arduino-cli lib install 'USB Host Shield 2.0'

      - name: Build and Test
        run: |
          arduino-cli compile --fqbn arduino:avr:uno . > test_results.txt
        env:
          ARDUINO_BOARD: 'arduino:avr:uno'

      - name: Report Results as Comment
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          TOKEN="$GITHUB_TOKEN"
          COMMENT="Test results:

          \`\`\`
          $(cat test_results.txt)
          \`\`\`"
          API_URL="https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments"

          curl -X POST -H "Authorization: token $TOKEN" -d "{\"body\":\"$COMMENT\"}" "$API_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # You can add additional steps for testing if needed.