name: arduino_cli
 
on: [push, pull_request]
 
jobs:
  test-matrix:
    strategy:
      matrix:
        arduino-platform: ["arduino:avr"]
        include:
          - arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:uno"

    runs-on: windows-latest
    steps:

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1.1.1
   
    - name: Install platform
      run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
    
    - name: arduino/arduino-lint-action
  # You may pin to the exact commit or the version.
  # uses: arduino/arduino-lint-action@34273a972ebf4575065aaede94a51632888d7452
      uses: arduino/arduino-lint-action@v1.0.0
      with:
       version: 1.x
       library-manager: servo
       project-type: all
       verbose: true

    
    - name: Compile Sketch
      run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./blink
