name: arduino_cli
 
on: [push, pull_request]
 
jobs:
  test-matrix:
    strategy:
      matrix:
        arduino-platform: ["arduino:avr"]
        include:
          - arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:uno"

    runs-on: windows-latest
    steps:
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1.1.1
      with:
          path: ./
          version: 1.1.1
          library-manager: servo
          project-type: all
          verbose: true
    
    - name: Install platform
      run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
    
    - name: Compile Sketch
      run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./blink
