name: Arduino CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Target Branch'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Arduino
        uses: arduino/setup-arduino-cli@v1

      - name: Clone USB Host Shield 2.0 library from GitHub
        run: |
          git clone https://github.com/felis/USB_Host_Shield_2.0.git ~/Arduino/libraries/USB_Host_Shield_2.0

      - name: Install Arduino Libraries
        run: |
          arduino-cli lib install servo
          arduino-cli core install arduino:avr

      - name: Build and Test
        run: |
          arduino-cli compile --fqbn arduino:avr:uno .
        env:
          ARDUINO_BOARD: 'arduino:avr:uno'
        working-directory: ${{ github.workspace }}

      - name: Change Working Directory
        if: always()
        run: ls && cd build && ls

      - name: Comment on Pull Request
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const result = fs.readFileSync('Arduino-Robotic-Arm.ino.build.log', 'utf8');
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Arduino Build Results:\n```\n' + result + '\n```'
            });